import 'package:flutter/material.dart';

class Pallet {
  static const Color primary = Color(0xFF4CA6A8);
  static const Color white = Color(0xFFFFFFFF);
  static const Color wsBlue = Color(0xFFABB3C7);
  static const Color buttonOutline = Color(0xFFBBECED);
  static const Color bg = Color(0xFF1B1E26);
  static const Color outlineBorder2 = Color(0xFF2F3540);
  static const Color validateGreen = Color(0xFF22B07D);
  static const Color divider = Color(0xFF848A99);
  static const Color visible = Color(0xFFC6CFE5);
  static const Color sliderOrange = Color(0xFFFF8700);
  static const Color sliderBlue = Color(0xFFD8DFEB);
  static const Color reviewCont = Color(0xFFFFF5DC);
  static const Color meLeaderboard = Color(0xFFEDE2BB);

  static const Color secondary = Color(0XFF052370);
  static const Color secondaryLight = Color(0xFF8291BB);
  static const Color oneApp = Color(0xFF242424);
  static const Color outlineBorder = Color(0xFFBEBEBE);
  static const Color whiteArrBg = Color(0xFFF8FCFF);
  static const Color greyWallet = Color(0xff8C8C8C);
  static const Color greyDetailsTr = Color(0xFF737373);
  static const Color black = Color(0xFF000000);
  static const Color greyO = Color(0xFFD0D0D0);
  static const Color greyOb = Color(0xFF686868);
  static const Color grey3 = Color(0XFFCCCCCC);
  static const Color greyish = Color(0xFFF3F3F3);
  static const Color greyAccSub = Color(0xFFA9A9A9);
  static const Color greyNavB = Color(0xFFE8E3E3);
  static const Color greyHomeAdd = Color(0xFF888C93);
  static const Color greyErrCash = Color(0xFFE5E5E5);
  static const Color greyContactUs = Color(0xFFEFEFEF);
  static const Color greyContactUs2 = Color(0xFF878787);
  static const Color grey900 = Color(0xFF111928);
  static const Color grey800 = Color(0xFF1F2A37);
  static const Color grey500 = Color(0xFF6B7280);
  static const Color grey300 = Color(0xFFD1D5DB);
  static const Color grey100 = Color(0xFFF3F4F6);
  static const Color greyNotif = Color(0xFF6E6161);
  static const Color greyNotifDiv = Color(0xFFE7E7E7);
  static const Color greyScale = Color(0xFF464F54);
  static const Color marktRun = Color(0xFFFFDCCC);
  static const Color marktRun1 = Color(0xFF266472);
  static const Color hhItems = Color(0xFFCDECE3);
  static const Color hhItems1 = Color(0xFF07A072);
  static const Color beauRun = Color(0xFFFFEECC);
  static const Color beauRun1 = Color(0xFFFEA800);
  static const Color quickActs = Color(0xFFF5F6F9);
  static const Color midnight = Color(0xFF1B1D28);
  static const Color lightOrange = Color(0xFFFeF8F5);

  static const Color borderUnfocus = Color(0xFFE3E3E3);
  static const Color green = Color(0xFF2A6E4F);
  static const Color greenTransC = Color(0xFF0E996F);
  static const Color accountHeader = Color(0xFFF5FBFF);
  static const Color tabBar = Color(0xFFF6F6F6);
  static const Color blue = Color(0xFF1E90FF);
  static const Color darkBlue = Color(0xFF010716);
  static const Color lightBlue = Color(0xFFCDD3E2);
  static const Color redWallet = Color(0xFFC30000);
  static const Color redBadge = Color(0xFFC00101);

  static const Color red = Color(0xFFD64927);
  static const Color borderLight = Color(0xFFF9FAF9);
  static const Color border1 = Color(0xFFD6F6D5);
  static const Color error = Color(0XFFFF3737);
  static const Color grey = Color(0XFF777777);
  static const Color grey1 = Color(0XFF555555);
  static const Color shadowGreen = Color(0XFF5EC17F);
  static const Color orange = Color(0xFFD64927);
}
